 //Cliente
export const CLIENTE_LOGIN = 'CLIENTE_LOGIN';
export const CLIENTE_OBTENER_POR_ID_FIREBASE = 'CLIENTE_OBTENER_POR_ID_FIREBASE';
export const CLIENTE_REGISTRO = 'CLIENTE_REGISTRO';
export const CLIENTE_ACTUALIZAR_DATOS_PERSONALES = 'CLIENTE_ACTUALIZAR_DATOS_PERSONALES';
export const CLIENTE_ACTUALIZAR_VEHICULOS = 'CLIENTE_ACTUALIZAR_VEHICULOS';
export const CLIENTE_ACTUALIZAR_PAGOS = 'CLIENTE_ACTUALIZAR_PAGOS';
export const CLIENTE_ACTUALIZAR = 'CLIENTE_ACTUALIZAR';
export const CLIENTE_GUARDAR_FOTO_PERFIL = 'CLIENTE_GUARDAR_FOTO_PERFIL';
export const CLIENTE_GUARDAR_FOTO_VEHICULO = 'CLIENTE_GUARDAR_FOTO_VEHICULO';
export const RESTABLECER_CONTRASENA = "RESTABLECER_CONTRASENA";
export const OBTENER_HISTORIAL_SERVICIOS = "OBTENER_HISTORIAL_SERVICIOS";
export const LOG_OUT="LOG_OUT";
// Cliente- Conekta
export const CLIENTE_CONEKTA_CREAR = "CLIENTE_CONEKTA_CREAR"
export const CLIENTE_CONEKTA_ELIMINAR_FORMA_PAGO = "CLIENTE_CONEKTA_ELIMINAR_FORMA_PAGO"
export const CLIENTE_CONEKTA_AGREGAR_FORMA_PAGO = "CLIENTE_CONEKTA_AGREGAR_FORMA_PAGO"



//Solicitud
export const SOLICITUD_ACTUALIZAR_TIPOSERVICIO = "SOLICITUD_ACTUALIZAR_TIPOSERVICIO";
export const SOLICITUD_ACTUALIZAR_ID_VEHICULO= "SOLICITUD_ACTUALIZAR_ID_VEHICULO";
export const SOLICITUD_PROVEEDOR_SELECCIONADO = 'SOLICITUD_PROVEEDOR_SELECCIONADO';
export const SOLICITUD_ACTUALIZAR_ID_CLIENTE = 'SOLICITUD_ACTUALIZAR_ID_CLIENTE';
export const SOLICITUD_CREAR_DB = 'SOLICITUD_CREAR_DB';
export const SOLICITUD_ACTUALIZAR_DB = 'SOLICITUD_ACTUALIZAR_DB';
export const SOLICITUD_ACTUALIZAR_ID_METODOPAGO = 'SOLICITUD_ACTUALIZAR_ID_METODOPAGO';
export const SOLICITUD_ACTUALIZAR_STATUS ='SOLICITUD_ACTUALIZAR_STATUS';
export const SOLICITUD_CONEKTA_CREAR_ORDEN = "SOLICITUD_CONEKTA_CREAR_ORDEN"
export const SOLICITUD_ENVIAR_EMAIL_PAGO = "SOLICITUD_ENVIAR_EMAIL_PAGO"


// Solicitud backend
export const SOLICITUD_ENVIAR ='SOLICITUD_ENVIAR';

//Proveedor 
export const PROVEEDOR_OBTENER_POR_ESTADO_SERVICIO = 'PROVEEDOR_OBTENER_POR_ESTADO_SERVICIO';

// Catalogos
export const CATALOGO_OBTENER_MARCAS_MODELO = 'CATALOGO_OBTENER_MARCAS_MODELO';